# Generated by Django 5.2.14 on 2026-05-15 00:46

import django.db.models.deletion
import django.utils.timezone
import services.emprunts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'emprunt")),
                ('due_date', models.DateField(default=services.emprunts.models.default_due_date, verbose_name='Date de retour prévue')),
                ('returned_at', models.DateField(blank=True, null=True, verbose_name='Date de retour effective')),
                ('status', models.CharField(choices=[('active', 'En cours'), ('returned', 'Retourné'), ('overdue', 'En retard'), ('renewed', 'Renouvelé')], default='active', max_length=10, verbose_name='Statut')),
                ('renewal_count', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True, verbose_name='Notes bibliothécaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='books.book', verbose_name='Livre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to=settings.AUTH_USER_MODEL, verbose_name='Emprunteur')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'verbose_name_plural': 'Emprunts',
                'ordering': ['-borrowed_at'],
                'indexes': [models.Index(fields=['status'], name='loans_loan_status_962e99_idx'), models.Index(fields=['user', 'status'], name='loans_loan_user_id_d0fb34_idx'), models.Index(fields=['due_date'], name='loans_loan_due_dat_1042a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('ready', 'Disponible – à récupérer'), ('fulfilled', 'Honorée'), ('cancelled', 'Annulée')], default='pending', max_length=12)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['reserved_at'],
                'unique_together': {('user', 'book', 'status')},
            },
        ),
    ]
