# Generated by Django 5.2.14 on 2026-05-15 00:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Catégorie')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titre')),
                ('author', models.CharField(max_length=200, verbose_name='Auteur(s)')),
                ('isbn', models.CharField(help_text='Format: 978-X-XXXXX-XXX-X', max_length=17, unique=True, verbose_name='ISBN')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='Éditeur')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année de publication')),
                ('pages', models.PositiveIntegerField(blank=True, null=True, verbose_name='Nombre de pages')),
                ('language', models.CharField(default='Français', max_length=30, verbose_name='Langue')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Couverture')),
                ('keywords', models.CharField(blank=True, help_text='Séparés par des virgules', max_length=300, verbose_name='Mots-clés')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name="Nombre total d'exemplaires")),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='Exemplaires disponibles')),
                ('location', models.CharField(blank=True, help_text='Ex: DIT Campus – Zone A', max_length=100, verbose_name='Localisation')),
                ('call_number', models.CharField(blank=True, max_length=50, verbose_name='Numéro de cote')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note (1–5)')),
                ('comment', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='books.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis lecteurs',
                'ordering': ['-created_at'],
                'unique_together': {('book', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['isbn'], name='books_book_isbn_54becd_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='books_book_author_b941fe_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='books_book_title_d3218d_idx'),
        ),
    ]
